package tr

// dictEntries maps normalized English words/phrases to their Chinese translations.
// Coverage: ~400 common words + short phrases for offline EN→ZH translation.
var dictEntries = map[string]string{
	// Greetings & common expressions
	"hello":                 "你好",
	"hi":                    "你好",
	"hey":                   "嗨",
	"world":                 "世界",
	"good":                  "好的",
	"bad":                   "坏的",
	"yes":                   "是",
	"no":                    "不",
	"not":                   "不",
	"thank you":             "谢谢",
	"thanks":                "谢谢",
	"please":                "请",
	"sorry":                 "对不起",
	"help":                  "帮助",
	"ok":                    "好的",
	"okay":                  "好的",
	"love":                  "爱",
	"like":                  "喜欢",
	"hate":                  "讨厌",
	"nice":                  "不错",
	"great":                 "很棒",
	"wonderful":             "精彩",
	"terrible":              "可怕",
	"fine":                  "好的",

	// Time
	"time":                  "时间",
	"day":                   "天",
	"night":                 "晚上",
	"morning":               "早上",
	"afternoon":             "下午",
	"evening":               "傍晚",
	"today":                 "今天",
	"tomorrow":              "明天",
	"yesterday":             "昨天",
	"week":                  "星期",
	"month":                 "月",
	"year":                  "年",
	"hour":                  "小时",
	"minute":                "分钟",
	"moment":                "片刻",
	"now":                   "现在",
	"later":                 "以后",
	"soon":                  "很快",
	"before":                "之前",
	"after":                 "之后",
	"early":                 "早",
	"late":                  "晚",
	"always":                "总是",
	"never":                 "从不",
	"often":                 "经常",
	"sometimes":             "有时",
	"usually":               "通常",
	"already":               "已经",
	"still":                 "仍然",
	"yet":                   "还",

	// Numbers
	"one":                   "一",
	"two":                   "二",
	"three":                 "三",
	"four":                  "四",
	"five":                  "五",
	"six":                   "六",
	"seven":                 "七",
	"eight":                 "八",
	"nine":                  "九",
	"ten":                   "十",
	"hundred":               "百",
	"thousand":              "千",
	"million":               "百万",
	"first":                 "第一",
	"second":                "第二",
	"third":                 "第三",
	"last":                  "最后",
	"next":                  "下一个",
	"many":                  "许多",
	"much":                  "很多",
	"more":                  "更多",
	"less":                  "更少",
	"few":                   "少数",
	"some":                  "一些",
	"any":                   "任何",
	"all":                   "全部",
	"every":                 "每个",
	"each":                  "每个",
	"both":                  "两个",
	"none":                  "没有",

	// Weather & nature
	"weather":               "天气",
	"sun":                   "太阳",
	"moon":                  "月亮",
	"star":                  "星星",
	"rain":                  "雨",
	"snow":                  "雪",
	"wind":                  "风",
	"cloud":                 "云",
	"sky":                   "天空",
	"earth":                 "地球",
	"fire":                  "火",
	"river":                 "河",
	"mountain":              "山",
	"sea":                   "海",
	"ocean":                 "海洋",
	"tree":                  "树",
	"flower":                "花",
	"grass":                 "草",
	"forest":                "森林",
	"air":                   "空气",
	"hot":                   "热",
	"cold":                  "冷",
	"warm":                  "温暖",
	"cool":                  "凉爽",
	"dry":                   "干燥",
	"wet":                   "湿",

	// Size & description
	"big":                   "大",
	"small":                 "小",
	"large":                 "大",
	"little":                "小",
	"long":                  "长",
	"short":                 "短",
	"tall":                  "高",
	"high":                  "高",
	"low":                   "低",
	"wide":                  "宽",
	"narrow":                "窄",
	"deep":                  "深",
	"thick":                 "厚",
	"thin":                  "薄",
	"heavy":                 "重",
	"light":                 "轻",
	"fast":                  "快",
	"slow":                  "慢",
	"quick":                 "快速",
	"strong":                "强壮",
	"weak":                  "弱",
	"hard":                  "硬",
	"soft":                  "软",
	"new":                   "新",
	"old":                   "旧",
	"young":                 "年轻",
	"beautiful":             "美丽",
	"pretty":                "漂亮",
	"ugly":                  "丑陋",
	"rich":                  "富有",
	"poor":                  "贫穷",
	"clean":                 "干净",
	"dirty":                 "脏",
	"full":                  "满",
	"empty":                 "空",
	"easy":                  "容易",
	"difficult":             "困难",
	"simple":                "简单",
	"complex":               "复杂",
	"same":                  "相同",
	"different":             "不同",
	"important":             "重要",
	"special":               "特别",
	"common":                "常见",
	"normal":                "正常",
	"strange":               "奇怪",
	"true":                  "真的",
	"false":                 "假的",
	"real":                  "真实",
	"right":                 "正确",
	"wrong":                 "错误",
	"possible":              "可能",
	"necessary":             "必要",
	"sure":                  "确定",
	"maybe":                 "可能",
	"perhaps":               "也许",
	"also":                  "也",
	"too":                   "太",
	"very":                  "非常",
	"just":                  "刚刚",
	"only":                  "只有",
	"even":                  "甚至",
	"quite":                 "相当",
	"really":                "真的",
	"almost":                "几乎",
	"enough":                "足够",
	"together":              "一起",

	// Emotions & states
	"happy":                 "快乐",
	"sad":                   "悲伤",
	"angry":                 "生气",
	"excited":               "兴奋",
	"afraid":                "害怕",
	"scared":                "害怕",
	"worried":               "担心",
	"surprised":             "惊讶",
	"bored":                 "无聊",
	"tired":                 "累",
	"hungry":                "饿",
	"thirsty":               "渴",
	"sick":                  "生病",
	"healthy":               "健康",
	"sleep":                 "睡觉",
	"awake":                 "醒着",
	"alive":                 "活着",
	"dead":                  "死亡",
	"busy":                  "忙",
	"free":                  "空闲",
	"ready":                 "准备好",
	"safe":                  "安全",
	"dangerous":             "危险",

	// Food & drink
	"food":                  "食物",
	"water":                 "水",
	"bread":                 "面包",
	"rice":                  "米饭",
	"meat":                  "肉",
	"fish":                  "鱼",
	"fruit":                 "水果",
	"vegetable":             "蔬菜",
	"egg":                   "鸡蛋",
	"milk":                  "牛奶",
	"cheese":                "奶酪",
	"butter":                "黄油",
	"sugar":                 "糖",
	"salt":                  "盐",
	"oil":                   "油",
	"tea":                   "茶",
	"coffee":                "咖啡",
	"juice":                 "果汁",
	"beer":                  "啤酒",
	"wine":                  "葡萄酒",
	"eat":                   "吃",
	"drink":                 "喝",
	"cook":                  "烹饪",
	"taste":                 "品尝",
	"delicious":             "美味",
	"sweet":                 "甜",
	"sour":                  "酸",
	"bitter":                "苦",
	"spicy":                 "辣",

	// People & relationships
	"man":                   "男人",
	"woman":                 "女人",
	"child":                 "孩子",
	"baby":                  "婴儿",
	"people":                "人们",
	"person":                "人",
	"family":                "家庭",
	"friend":                "朋友",
	"father":                "父亲",
	"mother":                "母亲",
	"parent":                "父母",
	"brother":               "兄弟",
	"sister":                "姐妹",
	"son":                   "儿子",
	"daughter":              "女儿",
	"husband":               "丈夫",
	"wife":                  "妻子",
	"boyfriend":             "男朋友",
	"girlfriend":            "女朋友",
	"neighbor":              "邻居",
	"teacher":               "老师",
	"student":               "学生",
	"doctor":                "医生",
	"nurse":                 "护士",
	"police":                "警察",
	"boss":                  "老板",
	"name":                  "名字",
	"age":                   "年龄",
	"birthday":              "生日",
	"address":               "地址",

	// Places
	"home":                  "家",
	"house":                 "房子",
	"room":                  "房间",
	"door":                  "门",
	"window":                "窗户",
	"wall":                  "墙",
	"floor":                 "地板",
	"table":                 "桌子",
	"chair":                 "椅子",
	"bed":                   "床",
	"kitchen":               "厨房",
	"bathroom":              "浴室",
	"garden":                "花园",
	"city":                  "城市",
	"town":                  "城镇",
	"village":               "村庄",
	"country":               "国家",
	"street":                "街道",
	"road":                  "路",
	"bridge":                "桥",
	"building":              "建筑",
	"school":                "学校",
	"hospital":              "医院",
	"library":               "图书馆",
	"market":                "市场",
	"shop":                  "商店",
	"restaurant":            "餐厅",
	"hotel":                 "酒店",
	"park":                  "公园",
	"bank":                  "银行",
	"office":                "办公室",
	"airport":               "机场",
	"station":               "车站",

	// Technology & objects
	"book":                  "书",
	"pen":                   "笔",
	"paper":                 "纸",
	"phone":                 "电话",
	"computer":              "电脑",
	"internet":              "互联网",
	"email":                 "电子邮件",
	"message":               "消息",
	"screen":                "屏幕",
	"keyboard":              "键盘",
	"mouse":                 "鼠标",
	"camera":                "相机",
	"television":            "电视",
	"radio":                 "收音机",
	"car":                   "汽车",
	"bus":                   "公共汽车",
	"train":                 "火车",
	"airplane":              "飞机",
	"ship":                  "船",
	"bicycle":               "自行车",
	"ticket":                "票",
	"money":                 "钱",
	"price":                 "价格",
	"cost":                  "费用",
	"cheap":                 "便宜",
	"expensive":             "昂贵",
	"key":                   "钥匙",
	"box":                   "盒子",
	"bag":                   "包",
	"clothes":               "衣服",

	// Actions
	"go":                    "去",
	"come":                  "来",
	"see":                   "看见",
	"look":                  "看",
	"hear":                  "听见",
	"listen":                "听",
	"speak":                 "说话",
	"say":                   "说",
	"tell":                  "告诉",
	"ask":                   "问",
	"answer":                "回答",
	"read":                  "读",
	"write":                 "写",
	"learn":                 "学习",
	"teach":                 "教",
	"know":                  "知道",
	"understand":            "理解",
	"think":                 "想",
	"believe":               "相信",
	"feel":                  "感觉",
	"want":                  "想要",
	"need":                  "需要",
	"have":                  "有",
	"make":                  "做",
	"do":                    "做",
	"get":                   "得到",
	"give":                  "给",
	"take":                  "拿",
	"use":                   "使用",
	"find":                  "找到",
	"keep":                  "保持",
	"let":                   "让",
	"put":                   "放",
	"call":                  "打电话",
	"try":                   "尝试",
	"wait":                  "等待",
	"walk":                  "走路",
	"run":                   "跑",
	"swim":                  "游泳",
	"play":                  "玩",
	"work":                  "工作",
	"buy":                   "买",
	"sell":                  "卖",
	"pay":                   "支付",
	"send":                  "发送",
	"receive":               "接收",
	"open":                  "打开",
	"close":                 "关闭",
	"start":                 "开始",
	"begin":                 "开始",
	"stop":                  "停止",
	"finish":                "完成",
	"end":                   "结束",
	"continue":              "继续",
	"change":                "改变",
	"choose":                "选择",
	"decide":                "决定",
	"follow":                "跟随",
	"remember":              "记得",
	"forget":                "忘记",
	"meet":                  "见面",
	"leave":                 "离开",
	"return":                "返回",
	"arrive":                "到达",
	"move":                  "移动",
	"bring":                 "带来",
	"carry":                 "携带",
	"catch":                 "抓住",
	"push":                  "推",
	"pull":                  "拉",
	"break":                 "打破",
	"fix":                   "修理",
	"build":                 "建造",
	"create":                "创造",
	"grow":                  "成长",
	"live":                  "生活",
	"die":                   "死亡",
	"agree":                 "同意",
	"accept":                "接受",
	"refuse":                "拒绝",
	"allow":                 "允许",
	"check":                 "检查",

	// Common phrases
	"hello world":           "你好世界",
	"thank you very much":   "非常感谢",
	"nice to meet you":      "很高兴认识你",
	"how are you":           "你好吗",
	"i am fine":             "我很好",
	"good morning":          "早上好",
	"good afternoon":        "下午好",
	"good evening":          "晚上好",
	"good night":            "晚安",
	"goodbye":               "再见",
	"see you":               "再见",
	"see you later":         "回头见",
	"i love you":            "我爱你",
	"long time no see":      "好久不见",
	"what is your name":     "你叫什么名字",
	"my name is":            "我叫",
	"where are you from":    "你从哪里来",
	"i am from":             "我来自",
	"how much":              "多少钱",
	"how many":              "多少",
	"i don't know":          "我不知道",
	"i don't understand":    "我不明白",
	"can you help me":       "你能帮我吗",
	"of course":             "当然",
	"no problem":            "没问题",
	"no thanks":             "不用了，谢谢",
	"you are welcome":       "不客气",
	"take care":             "保重",
	"have a nice day":       "祝你有美好的一天",
	"happy birthday":        "生日快乐",
	"happy new year":        "新年快乐",
	"merry christmas":       "圣诞快乐",
	"congratulations":       "恭喜",
	"welcome":               "欢迎",
	"excuse me":             "打扰一下",
	"i am sorry":            "我很抱歉",
	"never mind":            "没关系",
	"that is right":         "没错",
	"by the way":            "顺便说一句",
	"in fact":               "事实上",
	"for example":           "例如",
	"at least":              "至少",
	"at first":              "起初",
	"at last":               "终于",
	"as soon as possible":   "尽快",
	"a lot of":              "许多",
	"a little":              "一点",
	"all right":             "好吧",
	"come on":               "来吧",
	"come in":               "请进",
	"come back":             "回来",
	"go out":                "出去",
	"go back":               "回去",
	"get up":                "起床",
	"wake up":               "醒来",
	"hurry up":              "快点",
	"look for":              "寻找",
	"wait for":              "等待",
	"look at":               "看",
	"listen to":             "听",
	"think about":           "考虑",
	"talk about":            "谈论",
	"look forward to":       "期待",
	"depend on":             "取决于",
	"belong to":             "属于",
}
